### ISSUE TITLE
Preserve menuindex and parent on updates

### ISSUE THREAD

**Issue by sebastian-marinescu** [BobRay/LogPageNotFound#3]
Hi Bob, 

I love your plugin and use it for years now. It helps in SEO or hacker-attacks alike 😄 Thank you for it ❤️  

In my setups I have the created resource inside a "system"-container (which just hides some resources from the editors). 
Now every time I update the package, I've noticed that the `Page Not Found Log Report` resource is taken out of this container and put inside the root at the very top. I then have to drag it back to its righteous place. 

This is a little bit annoying when you have to update the package on multiple sites (especially when you plan to automate this), 
and in my opinion this is also unexpected behavior.

It would be ideal if the resource keeps its parent and also the menu-index inside it.

**Comment by BobRay** [comment]
Sorry about that. It's a side effect of how the resource resolver works. I think I've fixed It. If there's ever another release, let me know if it doesn't work.

**Comment by sebastian-marinescu** [comment]
Nice, thank you.
